export const SELECT_DIRECTORY = "SELECT_DIRECTORY";
export const TOGGLE_DIRECTORY = "TOGGLE_DIRECTORY";
export const OPEN_ROOT = "OPEN_ROOT";
export const UPDATE_PROJECT_FILES = "UPDATE_PROJECT_FILES";